export const GET_BOOKS_PENDING = "GET_BOOKS_PENDING"
export const GET_BOOKS_SUCCESS = "GET_BOOKS_SUCCESS"
export const GET_BOOKS_FAIL = "GET_BOOKS_FAIL"
export const GET_BOOKS_BY_SEARCH = "GET_BOOKS_BY_SEARCH"
