export const GET_CATEGORY_LIST_PENDING = "GET_CATEGORY_LIST_PENDING"
export const GET_CATEGORY_LIST_SUCCESS = "GET_CATEGORY_LIST_SUCCESS"
export const GET_CATEGORY_LIST_FAIL = "GET_CATEGORY_LIST_FAIL"
export const SET_ACTIVE_CATEGORY = "SET_ACTIVE_CATEGORY"
